---
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  showIcons: true
  showFileTree: true
  nerdFontsVersion: "3"

promptToReturnFromSubprocess: false

git:
  autoFetch: false
  autoRefresh: false
  autoForwardBranches: none
  pagers:
    - colorArg: always
      pager: "delta --paging=never --light"

os:
  editPreset: 'nvim'

keybinding:
  universal:
    quit: "q"
  files:
    commitChangesWithEditor: c
    commitChangesWithoutHook: C
