theme = "catppuccin_frappe"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.whitespace.render]
tab = "all"
space = "none"
newline = "none"

[editor.whitespace.characters]
tab = " "

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["spinner", "diagnostics", "workspace-diagnostics"]
center = []
right = ["position", "position-percentage"]

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
